### ISSUE TITLE
Initialize blog project

### ISSUE THREAD

**Issue by addroomberg** [addroomberg/bpra-blog#1]
As PO I want to have blog created using modern library/framework. In the scope of this issue blog project should be inited.

Technical requirements:
- React.JS/Angular.JS 

Following component structure should be inited:
- User list
- Profile info
- Modal form
- Header

Moreover it's needed too init router:
- /profile, /friends page for authenticated user
- /signup, /signin for not-authenticated

For now all backend requests can be mocked (including auth). Moreover we actively are using material components/icons, s it'll be great to init them as well.

**Comment by andriirymar** [comment]
Hi @addroomberg! if you don't mind I'll take the issue.

**Comment by addroomberg** [comment]
Sure!
