### ISSUE TITLE
Add sign up page

### ISSUE THREAD

**Issue by addroomberg** [addroomberg/bpra-blog#2]
As PO I want to have blog website created using modern library/framework. In the scope of this issue sign up page should be added. Form should has he following field:
- name
- username
- email
- address
- phone
- password
- company name

In addition to it "Sign up" button should be added.

Components should has the next view:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/87571501/190853297-cdc305a1-c6d6-4ce4-8316-0df42a8324f9.png">

_Note: for now all font can be ignored_

**Comment by andriirymar** [comment]
Hi @addroomberg! I can take it.
