### ISSUE TITLE
Add login page

### ISSUE THREAD

**Issue by addroomberg** [addroomberg/bpra-blog#3]
As PO I want to have blog website created using modern library/framework. In the scope of this issue login page should be added. Page should has he following field:
- username
- password

In addition to it "Sign in" button should be added.

Components should has the next view:

<img width="513" alt="image" src="https://user-images.githubusercontent.com/87571501/190853326-7a8051cf-40b0-4e0a-95a0-274dd09defc7.png">

_Note: for now all font can be ignored_

**Comment by andriirymar** [comment]
Hi @addroomberg! I can take it.

**Comment by andriirymar** [comment]
please review [these](https://github.com/addroomberg/bpra-blog/pull/8) changes
