### ISSUE TITLE
Add profile page

### ISSUE THREAD

**Issue by addroomberg** [addroomberg/bpra-blog#4]
As PO I want to have blog website created using modern library/framework. In the scope of this issue profile page should be added. Page should has he following field:

- name
- phone
- email
- website
- address

Component should has the next view:
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/87571501/190853383-87c34267-36b8-469f-aceb-8349ceb51347.png">

_Note: for now all font can be ignored_

**Comment by andriirymar** [comment]
Hi @addroomberg! I can take it.

**Comment by addroomberg** [comment]
Sure! Please let me know if you need any details
